
services:

  asset_builder:
    image: ${CYBER_DOJO_ASSET_BUILDER_IMAGE}:${CYBER_DOJO_ASSET_BUILDER_TAG}
    user: nobody
    build:
      args:
        - COMMIT_SHA
      context: .
    container_name: ${CYBER_DOJO_ASSET_BUILDER_CONTAINER_NAME}
    env_file: [ .env ]
    ports: [ "${CYBER_DOJO_ASSET_BUILDER_PORT}:${CYBER_DOJO_ASSET_BUILDER_PORT}" ]
    read_only: true
    restart: no
    volumes:
      - ./test/testdata/stylesheets:/app/app/assets/stylesheets:ro
      - ./test/testdata/javascripts:/app/app/assets/javascripts:ro
      - ./test:/app/test:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB
